### ISSUE TITLE
ImportError: No module named Crypto.Protocol.KDF

### ISSUE THREAD

**Issue by junkyarddog99** [arturoleon/warp-wallet-python#2]
I don't know if there's just a typo in the code or another thing that needs to be installed, but that's the message I get when trying to run the code.  I ran requirements again and it said I had all the needed stuff installed.

**Comment by arturoleon** [comment]
The package is listed in the requirements.txt file; it should be installed once you run `pip install -r requirements.txt`. Make sure that your python version is supported https://pypi.python.org/pypi/pycrypto
