### ISSUE TITLE
No return when i launch script

### ISSUE THREAD

**Issue by beuzathor** [arturoleon/warp-wallet-python#3]
I tried this git but i have no return when i launch my bashscript.
I make a file for test with this inside 
#!/usr/bin/env python

from warpWallet import generate_keypair;
generate_keypair("456789456", salt="123456")

But when i launch it with python myfyle.py system return nothing.
An idea for that problem ?

**Comment by arturoleon** [comment]
Generate pair returns a string with hexadecimal representation of the private key. You can use the following example to display the wallet address and key:
```
from warpWallet import generate_keypair
from keyUtils import keyToAddr,privateKeyToWif
privateKey = generate_keypair("456789456", salt="123456")
print("WIF: {}, Private key: {}").format(privateKeyToWif(privateKey), keyToAddr(privateKey))
```
